- name: Config Web with Docker
  hosts: elk
  become: true
  tasks:
  - name: Install Packages
    apt:
     force_apt_get: yes
     update_cache: yes
     name: docker.io
     state: present

  - name: set vm.max_map_count to 262144 in sysctl
    ansible.posix.sysctl:
      name: vm.max_map_count
      value: '262144'

  - name: Install pip3
    apt:
     force_apt_get: yes
     name: python3-pip
     state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044


